<?php

namespace Container9AWHzEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QoJyUVbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QoJyUVb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploader' => ['privates', 'App\\Service\\Media\\ImageUploader', 'getImageUploaderService', true],
        ], [
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'entityManager' => '?',
            'imageUploader' => 'App\\Service\\Media\\ImageUploader',
        ]);

        if (isset($container->privates['.service_locator.QoJyUVb'])) {
            return $container->privates['.service_locator.QoJyUVb'];
        }

        return $container->privates['.service_locator.QoJyUVb'] = $instance;
    }
}
