<?php

namespace Container9AWHzEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SScGLk_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sScGLk.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sScGLk.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'postImageRepository' => ['privates', 'App\\Repository\\PostImageRepository', 'getPostImageRepositoryService', true],
            'postLikeRepository' => ['privates', 'App\\Repository\\PostLikeRepository', 'getPostLikeRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'postImageRepository' => 'App\\Repository\\PostImageRepository',
            'postLikeRepository' => 'App\\Repository\\PostLikeRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
        ]);
    }
}
