<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PxVVPssService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PxVVPss' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameFavoriteRepository' => ['privates', 'App\\Repository\\GameFavoriteRepository', 'getGameFavoriteRepositoryService', true],
            'gamePopularityService' => ['privates', 'App\\Service\\Catalog\\GamePopularityService', 'getGamePopularityServiceService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gameFavoriteRepository' => 'App\\Repository\\GameFavoriteRepository',
            'gamePopularityService' => 'App\\Service\\Catalog\\GamePopularityService',
            'gameRepository' => 'App\\Repository\\GameRepository',
        ]);

        if (isset($container->privates['.service_locator.PxVVPss'])) {
            return $container->privates['.service_locator.PxVVPss'];
        }

        return $container->privates['.service_locator.PxVVPss'] = $instance;
    }
}
