<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X6Jn0gKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x6Jn0gK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'entityManager' => '?',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.x6Jn0gK'])) {
            return $container->privates['.service_locator.x6Jn0gK'];
        }

        return $container->privates['.service_locator.x6Jn0gK'] = $instance;
    }
}
