<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KIJKvJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._KIJKvJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._KIJKvJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatModerationDecisionService' => ['privates', 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService', 'getChatModerationDecisionServiceService', true],
            'moderationFeedbackFormatter' => ['privates', 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter', 'getModerationFeedbackFormatterService', true],
        ], [
            'chatModerationDecisionService' => 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService',
            'moderationFeedbackFormatter' => 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter',
        ]);
    }
}
