<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GS2Y49Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g_s2Y49' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g_s2Y49'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
        ], [
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
        ]);
    }
}
