<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_94HrWv6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.94HrWv6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.94HrWv6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistant' => ['privates', 'App\\Service\\Ai\\TournamentAiAssistantService', 'getTournamentAiAssistantServiceService', true],
            'tournamentRequestRepository' => ['privates', 'App\\Repository\\TournamentRequestRepository', 'getTournamentRequestRepositoryService', true],
        ], [
            'assistant' => 'App\\Service\\Ai\\TournamentAiAssistantService',
            'tournamentRequestRepository' => 'App\\Repository\\TournamentRequestRepository',
        ]);
    }
}
