<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRZYG1nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DRZYG1n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gamePopularityService' => ['privates', 'App\\Service\\Catalog\\GamePopularityService', 'getGamePopularityServiceService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'gamePopularityService' => 'App\\Service\\Catalog\\GamePopularityService',
            'gameRepository' => 'App\\Repository\\GameRepository',
        ]);

        if (isset($container->privates['.service_locator.DRZYG1n'])) {
            return $container->privates['.service_locator.DRZYG1n'];
        }

        return $container->privates['.service_locator.DRZYG1n'] = $instance;
    }
}
