<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KqrTeXeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KqrTeXe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KqrTeXe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistedGenerationService' => ['privates', 'App\\Service\\Ai\\Generation\\AssistedGenerationService', 'getAssistedGenerationServiceService', true],
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
        ], [
            'assistedGenerationService' => 'App\\Service\\Ai\\Generation\\AssistedGenerationService',
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
        ]);
    }
}
