<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssistedGenerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\Generation\AssistedGenerationService' shared autowired service.
     *
     * @return \App\Service\Ai\Generation\AssistedGenerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Generation'.\DIRECTORY_SEPARATOR.'AssistedGenerationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Generation'.\DIRECTORY_SEPARATOR.'RemoteContentGenerationInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Generation'.\DIRECTORY_SEPARATOR.'OpenAiRemoteContentGenerationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Generation'.\DIRECTORY_SEPARATOR.'LocalFallbackGenerationService.php';

        return $container->privates['App\\Service\\Ai\\Generation\\AssistedGenerationService'] = new \App\Service\Ai\Generation\AssistedGenerationService(new \App\Service\Ai\Generation\OpenAiRemoteContentGenerationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), new \App\Service\Ai\Generation\LocalFallbackGenerationService());
    }
}
