<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatModerationDecisionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\Moderation\ChatModerationDecisionService' shared autowired service.
     *
     * @return \App\Service\Ai\Moderation\ChatModerationDecisionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Moderation'.\DIRECTORY_SEPARATOR.'ChatModerationDecisionService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Moderation'.\DIRECTORY_SEPARATOR.'MessageRiskSignalAnalyzer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Moderation'.\DIRECTORY_SEPARATOR.'ChatCategoryClassifier.php';

        return $container->privates['App\\Service\\Ai\\Moderation\\ChatModerationDecisionService'] = new \App\Service\Ai\Moderation\ChatModerationDecisionService(new \App\Service\Ai\Moderation\MessageRiskSignalAnalyzer(), new \App\Service\Ai\Moderation\ChatCategoryClassifier());
    }
}
