<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGamePopularityServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Catalog\GamePopularityService' shared autowired service.
     *
     * @return \App\Service\Catalog\GamePopularityService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Catalog'.\DIRECTORY_SEPARATOR.'GamePopularityService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Catalog\\GamePopularityService'])) {
            return $container->privates['App\\Service\\Catalog\\GamePopularityService'];
        }

        $instance = new \App\Service\Catalog\GamePopularityService(($container->privates['App\\Repository\\GameRepository'] ?? $container->load('getGameRepositoryService')), ($container->privates['App\\Repository\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')), ($container->privates['App\\Repository\\TournamentTeamRepository'] ?? $container->load('getTournamentTeamRepositoryService')), ($container->privates['App\\Repository\\GameFavoriteRepository'] ?? $container->load('getGameFavoriteRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\Catalog\\GamePopularityService'])) {
            return $container->privates['App\\Service\\Catalog\\GamePopularityService'];
        }

        return $container->privates['App\\Service\\Catalog\\GamePopularityService'] = $instance;
    }
}
