<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameAiRemoteClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\Game\GameAiRemoteClient' shared autowired service.
     *
     * @return \App\Service\Ai\Game\GameAiRemoteClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'GameAiRemoteClient.php';

        return $container->privates['App\\Service\\Ai\\Game\\GameAiRemoteClient'] = new \App\Service\Ai\Game\GameAiRemoteClient(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
