<?php

namespace ContainerSxNwwTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamRosterPdfServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Captain\TeamRosterPdfService' shared autowired service.
     *
     * @return \App\Service\Captain\TeamRosterPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Captain'.\DIRECTORY_SEPARATOR.'TeamRosterPdfService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'PdfImageResolver.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'TableExportService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Service\\Captain\\TeamRosterPdfService'])) {
            return $container->privates['App\\Service\\Captain\\TeamRosterPdfService'];
        }

        $instance = new \App\Service\Captain\TeamRosterPdfService(($container->privates['App\\Repository\\TeamMemberRepository'] ?? $container->load('getTeamMemberRepositoryService')), ($container->privates['App\\Repository\\TeamJoinRequestRepository'] ?? $container->load('getTeamJoinRequestRepositoryService')), ($container->privates['App\\Service\\Admin\\PdfImageResolver'] ??= new \App\Service\Admin\PdfImageResolver(($container->services['kernel'] ?? $container->get('kernel', 1)))), ($container->privates['App\\Service\\Admin\\TableExportService'] ??= new \App\Service\Admin\TableExportService()), $a);

        if (isset($container->privates['App\\Service\\Captain\\TeamRosterPdfService'])) {
            return $container->privates['App\\Service\\Captain\\TeamRosterPdfService'];
        }

        return $container->privates['App\\Service\\Captain\\TeamRosterPdfService'] = $instance;
    }
}
