<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDukwD3u\App_KernelLintContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDukwD3u/App_KernelLintContainer.php') {
    touch(__DIR__.'/ContainerDukwD3u.legacy');

    return;
}

if (!\class_exists(App_KernelLintContainer::class, false)) {
    \class_alias(\ContainerDukwD3u\App_KernelLintContainer::class, App_KernelLintContainer::class, false);
}

return new \ContainerDukwD3u\App_KernelLintContainer([
    'container.build_hash' => 'DukwD3u',
    'container.build_id' => 'cca2cd22',
    'container.build_time' => 1772171652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDukwD3u');
