<?php

namespace ContainerBge3C1C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I2ylD58Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i2ylD58' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamJoinRequestRepository' => ['privates', 'App\\Repository\\TeamJoinRequestRepository', 'getTeamJoinRequestRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
        ], [
            'entityManager' => '?',
            'teamJoinRequestRepository' => 'App\\Repository\\TeamJoinRequestRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);

        if (isset($container->privates['.service_locator.i2ylD58'])) {
            return $container->privates['.service_locator.i2ylD58'];
        }

        return $container->privates['.service_locator.i2ylD58'] = $instance;
    }
}
