<?php

namespace ContainerBge3C1C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QOtwL4aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qOtwL4a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qOtwL4a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedPostAssembler' => ['privates', 'App\\Service\\Post\\FeedPostAssembler', 'getFeedPostAssemblerService', true],
            'friendRequestRepository' => ['privates', 'App\\Repository\\FriendRequestRepository', 'getFriendRequestRepositoryService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'profilePageDataProvider' => ['privates', 'App\\Service\\Profile\\ProfilePageDataProvider', 'getProfilePageDataProviderService', true],
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamJoinRequestRepository' => ['privates', 'App\\Repository\\TeamJoinRequestRepository', 'getTeamJoinRequestRepositoryService', true],
        ], [
            'feedPostAssembler' => 'App\\Service\\Post\\FeedPostAssembler',
            'friendRequestRepository' => 'App\\Repository\\FriendRequestRepository',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
            'profilePageDataProvider' => 'App\\Service\\Profile\\ProfilePageDataProvider',
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamJoinRequestRepository' => 'App\\Repository\\TeamJoinRequestRepository',
        ]);
    }
}
