<?php

namespace ContainerBge3C1C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptainTeamContextProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Captain\CaptainTeamContextProvider' shared autowired service.
     *
     * @return \App\Service\Captain\CaptainTeamContextProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Captain'.\DIRECTORY_SEPARATOR.'CaptainTeamContextProvider.php';

        return $container->privates['App\\Service\\Captain\\CaptainTeamContextProvider'] = new \App\Service\Captain\CaptainTeamContextProvider(($container->privates['App\\Repository\\TeamRepository'] ?? self::getTeamRepositoryService($container)));
    }
}
