<?php

namespace ContainerBge3C1C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedPostAssemblerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Post\FeedPostAssembler' shared autowired service.
     *
     * @return \App\Service\Post\FeedPostAssembler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Post'.\DIRECTORY_SEPARATOR.'FeedPostAssembler.php';

        return $container->privates['App\\Service\\Post\\FeedPostAssembler'] = new \App\Service\Post\FeedPostAssembler(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\PostImageRepository'] ?? $container->load('getPostImageRepositoryService')), ($container->privates['App\\Repository\\PostLikeRepository'] ?? $container->load('getPostLikeRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));
    }
}
