<?php

namespace ContainerBge3C1C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImageRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ProductImageRepository' shared autowired service.
     *
     * @return \App\Repository\ProductImageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ProductImageRepository.php';

        return $container->privates['App\\Repository\\ProductImageRepository'] = new \App\Repository\ProductImageRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
