<?php

namespace Container4iAXR3l;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HmHPXAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hmHP_XA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'friendRequestRepository' => ['privates', 'App\\Repository\\FriendRequestRepository', 'getFriendRequestRepositoryService', true],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'friendRequestRepository' => 'App\\Repository\\FriendRequestRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.hmHP_XA'])) {
            return $container->privates['.service_locator.hmHP_XA'];
        }

        return $container->privates['.service_locator.hmHP_XA'] = $instance;
    }
}
