<?php

namespace Container4iAXR3l;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0SWUNmXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0SWUNmX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0SWUNmX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profilePageDataProvider' => ['privates', 'App\\Service\\Profile\\ProfilePageDataProvider', 'getProfilePageDataProviderService', true],
        ], [
            'profilePageDataProvider' => 'App\\Service\\Profile\\ProfilePageDataProvider',
        ]);
    }
}
