<?php

namespace Container4iAXR3l;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamInviteRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TeamInviteRepository' shared autowired service.
     *
     * @return \App\Repository\TeamInviteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'TeamInviteRepository.php';

        return $container->privates['App\\Repository\\TeamInviteRepository'] = new \App\Repository\TeamInviteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
