<?php

namespace ContainerYsXvA9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SoSH1zzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SoSH1zz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SoSH1zz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentRequestAiAssistantService' => ['privates', 'App\\Service\\Ai\\TournamentRequestAiAssistantService', 'getTournamentRequestAiAssistantServiceService', true],
            'tournamentRequestRepository' => ['privates', 'App\\Repository\\TournamentRequestRepository', 'getTournamentRequestRepositoryService', true],
        ], [
            'tournamentRequestAiAssistantService' => 'App\\Service\\Ai\\TournamentRequestAiAssistantService',
            'tournamentRequestRepository' => 'App\\Repository\\TournamentRequestRepository',
        ]);
    }
}
