<?php

namespace ContainerYsXvA9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MtHSHN0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MtHSHN0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartManager' => ['privates', 'App\\Service\\Shop\\CartManager', 'getCartManagerService', true],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'cartManager' => 'App\\Service\\Shop\\CartManager',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'entityManager' => '?',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);

        if (isset($container->privates['.service_locator.MtHSHN0'])) {
            return $container->privates['.service_locator.MtHSHN0'];
        }

        return $container->privates['.service_locator.MtHSHN0'] = $instance;
    }
}
