<?php

namespace ContainerYsXvA9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LCHqYhxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LCHqYhx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartItemRepository' => ['privates', 'App\\Repository\\CartItemRepository', 'getCartItemRepositoryService', true],
            'cartManager' => ['privates', 'App\\Service\\Shop\\CartManager', 'getCartManagerService', true],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'cartItemRepository' => 'App\\Repository\\CartItemRepository',
            'cartManager' => 'App\\Service\\Shop\\CartManager',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);

        if (isset($container->privates['.service_locator.LCHqYhx'])) {
            return $container->privates['.service_locator.LCHqYhx'];
        }

        return $container->privates['.service_locator.LCHqYhx'] = $instance;
    }
}
