<?php

namespace ContainerYsXvA9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilePageDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Profile\ProfilePageDataProvider' shared autowired service.
     *
     * @return \App\Service\Profile\ProfilePageDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Profile'.\DIRECTORY_SEPARATOR.'ProfilePageDataProvider.php';

        return $container->privates['App\\Service\\Profile\\ProfilePageDataProvider'] = new \App\Service\Profile\ProfilePageDataProvider(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\PostImageRepository'] ?? $container->load('getPostImageRepositoryService')), ($container->privates['App\\Repository\\PostLikeRepository'] ?? $container->load('getPostLikeRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Repository\\FriendshipRepository'] ?? $container->load('getFriendshipRepositoryService')), ($container->privates['App\\Repository\\FriendRequestRepository'] ?? $container->load('getFriendRequestRepositoryService')), ($container->privates['App\\Repository\\TeamMemberRepository'] ?? $container->load('getTeamMemberRepositoryService')));
    }
}
