<?php

namespace ContainerYsXvA9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRequestAiAssistantServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\TournamentRequestAiAssistantService' shared autowired service.
     *
     * @return \App\Service\Ai\TournamentRequestAiAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'TournamentRequestAiAssistantService.php';

        return $container->privates['App\\Service\\Ai\\TournamentRequestAiAssistantService'] = new \App\Service\Ai\TournamentRequestAiAssistantService(($container->privates['App\\Service\\Ai\\OllamaClientService'] ?? $container->load('getOllamaClientServiceService')));
    }
}
