<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6pXVFnQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6pXVFnQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'postImageUploader' => ['privates', 'App\\Service\\Post\\PostImageUploader', 'getPostImageUploaderService', true],
        ], [
            'entityManager' => '?',
            'postImageUploader' => 'App\\Service\\Post\\PostImageUploader',
        ]);

        if (isset($container->privates['.service_locator.6pXVFnQ'])) {
            return $container->privates['.service_locator.6pXVFnQ'];
        }

        return $container->privates['.service_locator.6pXVFnQ'] = $instance;
    }
}
