<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9fKbSLgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9fKbSLg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'entityManager' => '?',
            'postRepository' => 'App\\Repository\\PostRepository',
        ]);

        if (isset($container->privates['.service_locator.9fKbSLg'])) {
            return $container->privates['.service_locator.9fKbSLg'];
        }

        return $container->privates['.service_locator.9fKbSLg'] = $instance;
    }
}
