<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SzuzdYgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.szuzdYg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'entityManager' => '?',
            'gameRepository' => 'App\\Repository\\GameRepository',
        ]);

        if (isset($container->privates['.service_locator.szuzdYg'])) {
            return $container->privates['.service_locator.szuzdYg'];
        }

        return $container->privates['.service_locator.szuzdYg'] = $instance;
    }
}
