<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BxdMG2oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bxdMG2o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamJoinRequestRepository' => ['privates', 'App\\Repository\\TeamJoinRequestRepository', 'getTeamJoinRequestRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
        ], [
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'entityManager' => '?',
            'teamJoinRequestRepository' => 'App\\Repository\\TeamJoinRequestRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
        ]);

        if (isset($container->privates['.service_locator.bxdMG2o'])) {
            return $container->privates['.service_locator.bxdMG2o'];
        }

        return $container->privates['.service_locator.bxdMG2o'] = $instance;
    }
}
