<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LoginSuccessSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LoginSuccessSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'LoginSuccessSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\LoginSuccessSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LoginSuccessSubscriber'];
        }

        $instance = new \App\EventSubscriber\LoginSuccessSubscriber($a, ($container->services['router'] ?? self::getRouterService($container)));

        if (isset($container->privates['App\\EventSubscriber\\LoginSuccessSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LoginSuccessSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\LoginSuccessSubscriber'] = $instance;
    }
}
