<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostImageUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Post\PostImageUploader' shared autowired service.
     *
     * @return \App\Service\Post\PostImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Post'.\DIRECTORY_SEPARATOR.'PostImageUploader.php';

        return $container->privates['App\\Service\\Post\\PostImageUploader'] = new \App\Service\Post\PostImageUploader(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
