<?php

namespace ContainerZmQjMfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamMemberRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TeamMemberRepository' shared autowired service.
     *
     * @return \App\Repository\TeamMemberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'TeamMemberRepository.php';

        return $container->privates['App\\Repository\\TeamMemberRepository'] = new \App\Repository\TeamMemberRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
