<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJ6uCavService extends App_KernelLintContainer
{
    /*
     * Gets the private '.service_locator.tJ6uCav' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tJ6uCav'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profilePageDataProvider' => ['privates', 'App\\Service\\Profile\\ProfilePageDataProvider', 'getProfilePageDataProviderService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'profilePageDataProvider' => 'App\\Service\\Profile\\ProfilePageDataProvider',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
