<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISch2_EService extends App_KernelLintContainer
{
    /*
     * Gets the private '.service_locator.ISch2.e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'httpClient' => ['privates', 'http_client.uri_template', 'getHttpClient_UriTemplateService', true],
            'kernel' => ['services', 'kernel', 'getKernelService', true],
        ], [
            'entityManager' => '?',
            'httpClient' => '?',
            'kernel' => '?',
        ]);

        if (isset($container->privates['.service_locator.ISch2.e'])) {
            return $container->privates['.service_locator.ISch2.e'];
        }

        return $container->privates['.service_locator.ISch2.e'] = $instance;
    }
}
