<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cn2_TGXService extends App_KernelLintContainer
{
    /*
     * Gets the private '.service_locator.cn2.tGX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cn2.tGX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
        ]);
    }
}
