<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KiLOua_Service extends App_KernelLintContainer
{
    /*
     * Gets the private '.service_locator.KiLOua.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KiLOua.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'cartItemRepository' => ['privates', 'App\\Repository\\CartItemRepository', 'getCartItemRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'cartItemRepository' => 'App\\Repository\\CartItemRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);
    }
}
