<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SJtf5NsService extends App_KernelLintContainer
{
    /*
     * Gets the private '.service_locator.SJtf5Ns' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentRequestRepository' => ['privates', 'App\\Repository\\TournamentRequestRepository', 'getTournamentRequestRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentRequestRepository' => 'App\\Repository\\TournamentRequestRepository',
        ]);

        if (isset($container->privates['.service_locator.SJtf5Ns'])) {
            return $container->privates['.service_locator.SJtf5Ns'];
        }

        return $container->privates['.service_locator.SJtf5Ns'] = $instance;
    }
}
