<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiFriendRecommendationServiceService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Service\Friend\AiFriendRecommendationService' shared autowired service.
     *
     * @return \App\Service\Friend\AiFriendRecommendationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Friend\\AiFriendRecommendationService'] = new \App\Service\Friend\AiFriendRecommendationService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\FriendshipRepository'] ?? $container->load('getFriendshipRepositoryService')), ($container->privates['App\\Repository\\FriendRequestRepository'] ?? $container->load('getFriendRequestRepositoryService')), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
