<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartManagerService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Service\Shop\CartManager' shared autowired service.
     *
     * @return \App\Service\Shop\CartManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Shop\\CartManager'])) {
            return $container->privates['App\\Service\\Shop\\CartManager'];
        }

        $instance = new \App\Service\Shop\CartManager($a, ($container->privates['App\\Repository\\CartRepository'] ?? $container->load('getCartRepositoryService')), ($container->privates['App\\Repository\\CartItemRepository'] ?? $container->load('getCartItemRepositoryService')));

        if (isset($container->privates['App\\Service\\Shop\\CartManager'])) {
            return $container->privates['App\\Service\\Shop\\CartManager'];
        }

        return $container->privates['App\\Service\\Shop\\CartManager'] = $instance;
    }
}
