<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptainTeamContextProviderService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Service\Captain\CaptainTeamContextProvider' shared autowired service.
     *
     * @return \App\Service\Captain\CaptainTeamContextProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Captain\\CaptainTeamContextProvider'] = new \App\Service\Captain\CaptainTeamContextProvider(($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')));
    }
}
