<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendRequestRepositoryService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Repository\FriendRequestRepository' shared autowired service.
     *
     * @return \App\Repository\FriendRequestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FriendRequestRepository'] = new \App\Repository\FriendRequestRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
