<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedPostAssemblerService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Service\Post\FeedPostAssembler' shared autowired service.
     *
     * @return \App\Service\Post\FeedPostAssembler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Post\\FeedPostAssembler'] = new \App\Service\Post\FeedPostAssembler(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\PostImageRepository'] ?? $container->load('getPostImageRepositoryService')), ($container->privates['App\\Repository\\PostLikeRepository'] ?? $container->load('getPostLikeRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));
    }
}
