<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginController2Service extends App_KernelLintContainer
{
    /*
     * Gets the public 'App\Controller\Security\LoginController' shared autowired service.
     *
     * @return \App\Controller\Security\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Security\\LoginController'] = $instance = new \App\Controller\Security\LoginController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Security\\LoginController', $container));

        return $instance;
    }
}
