<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Cache_Resolver_DefaultService extends App_KernelLintContainer
{
    /*
     * Gets the public 'liip_imagine.cache.resolver.default' shared service.
     *
     * @return \Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['liip_imagine.cache.resolver.default'] = new \Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->privates['router.request_context'] ?? self::getRouter_RequestContextService($container)), (\dirname(__DIR__, 4).'/public'), 'media/cache');
    }
}
