<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductDetailController2Service extends App_KernelLintContainer
{
    /*
     * Gets the public 'App\Controller\Front\Page\ProductDetailController' shared autowired service.
     *
     * @return \App\Controller\Front\Page\ProductDetailController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Front\\Page\\ProductDetailController'] = $instance = new \App\Controller\Front\Page\ProductDetailController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Front\\Page\\ProductDetailController', $container));

        return $instance;
    }
}
