<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentAiAssistantServiceService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Service\Ai\TournamentAiAssistantService' shared autowired service.
     *
     * @return \App\Service\Ai\TournamentAiAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Ai\\TournamentAiAssistantService'] = new \App\Service\Ai\TournamentAiAssistantService(new \App\Service\Ai\OllamaClientService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));
    }
}
