<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentTypeService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Form\TournamentType' shared autowired service.
     *
     * @return \App\Form\TournamentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TournamentType'] = new \App\Form\TournamentType();
    }
}
