<?php

namespace ContainerDukwD3u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRepositoryService extends App_KernelLintContainer
{
    /*
     * Gets the private 'App\Repository\TournamentRepository' shared autowired service.
     *
     * @return \App\Repository\TournamentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TournamentRepository'] = new \App\Repository\TournamentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
