<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \App\Entity\Image implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'altText' => [parent::class, 'altText', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'fileUrl' => [parent::class, 'fileUrl', null, 16],
        "\0".parent::class."\0".'height' => [parent::class, 'height', null, 16],
        "\0".parent::class."\0".'imageId' => [parent::class, 'imageId', null, 16],
        "\0".parent::class."\0".'mimeType' => [parent::class, 'mimeType', null, 16],
        "\0".parent::class."\0".'sizeBytes' => [parent::class, 'sizeBytes', null, 16],
        "\0".parent::class."\0".'uploadedByUserId' => [parent::class, 'uploadedByUserId', null, 16],
        "\0".parent::class."\0".'width' => [parent::class, 'width', null, 16],
        'altText' => [parent::class, 'altText', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'fileUrl' => [parent::class, 'fileUrl', null, 16],
        'height' => [parent::class, 'height', null, 16],
        'imageId' => [parent::class, 'imageId', null, 16],
        'mimeType' => [parent::class, 'mimeType', null, 16],
        'sizeBytes' => [parent::class, 'sizeBytes', null, 16],
        'uploadedByUserId' => [parent::class, 'uploadedByUserId', null, 16],
        'width' => [parent::class, 'width', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
