<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null, 16],
        "\0".parent::class."\0".'birthDate' => [parent::class, 'birthDate', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'displayName' => [parent::class, 'displayName', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emailVerified' => [parent::class, 'emailVerified', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'passwordHash' => [parent::class, 'passwordHash', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'profileImageId' => [parent::class, 'profileImageId', null, 16],
        "\0".parent::class."\0".'resetPasswordExpiresAt' => [parent::class, 'resetPasswordExpiresAt', null, 16],
        "\0".parent::class."\0".'resetPasswordTokenHash' => [parent::class, 'resetPasswordTokenHash', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'twoFactorEnabled' => [parent::class, 'twoFactorEnabled', null, 16],
        "\0".parent::class."\0".'twoFactorEnabledAt' => [parent::class, 'twoFactorEnabledAt', null, 16],
        "\0".parent::class."\0".'twoFactorSecret' => [parent::class, 'twoFactorSecret', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        'bio' => [parent::class, 'bio', null, 16],
        'birthDate' => [parent::class, 'birthDate', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'displayName' => [parent::class, 'displayName', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emailVerified' => [parent::class, 'emailVerified', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'passwordHash' => [parent::class, 'passwordHash', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'profileImageId' => [parent::class, 'profileImageId', null, 16],
        'resetPasswordExpiresAt' => [parent::class, 'resetPasswordExpiresAt', null, 16],
        'resetPasswordTokenHash' => [parent::class, 'resetPasswordTokenHash', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'twoFactorEnabled' => [parent::class, 'twoFactorEnabled', null, 16],
        'twoFactorEnabledAt' => [parent::class, 'twoFactorEnabledAt', null, 16],
        'twoFactorSecret' => [parent::class, 'twoFactorSecret', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
        'username' => [parent::class, 'username', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
