<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P7eF9WdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p7eF9Wd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatModerationDecisionService' => ['privates', 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService', 'getChatModerationDecisionServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'moderationFeedbackFormatter' => ['privates', 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter', 'getModerationFeedbackFormatterService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'chatModerationDecisionService' => 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService',
            'entityManager' => '?',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'moderationFeedbackFormatter' => 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.p7eF9Wd'])) {
            return $container->privates['.service_locator.p7eF9Wd'];
        }

        return $container->privates['.service_locator.p7eF9Wd'] = $instance;
    }
}
