<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WtGxoMiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wtGxoMi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistedGenerationService' => ['privates', 'App\\Service\\Ai\\Generation\\AssistedGenerationService', 'getAssistedGenerationServiceService', true],
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'chatModerationDecisionService' => ['privates', 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService', 'getChatModerationDecisionServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'moderationFeedbackFormatter' => ['privates', 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter', 'getModerationFeedbackFormatterService', true],
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'assistedGenerationService' => 'App\\Service\\Ai\\Generation\\AssistedGenerationService',
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'chatModerationDecisionService' => 'App\\Service\\Ai\\Moderation\\ChatModerationDecisionService',
            'entityManager' => '?',
            'httpClient' => '?',
            'moderationFeedbackFormatter' => 'App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter',
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.wtGxoMi'])) {
            return $container->privates['.service_locator.wtGxoMi'];
        }

        return $container->privates['.service_locator.wtGxoMi'] = $instance;
    }
}
