<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Ue5SCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Ue5SC_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Ue5SC_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchTeamRepository' => ['privates', 'App\\Repository\\MatchTeamRepository', 'getMatchTeamRepositoryService', true],
            'pdfImageResolver' => ['privates', 'App\\Service\\Admin\\PdfImageResolver', 'getPdfImageResolverService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
        ], [
            'matchTeamRepository' => 'App\\Repository\\MatchTeamRepository',
            'pdfImageResolver' => 'App\\Service\\Admin\\PdfImageResolver',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
        ]);
    }
}
