<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9gW4ntService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9g_W4nt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9g_W4nt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'productImageRepository' => ['privates', 'App\\Repository\\ProductImageRepository', 'getProductImageRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'gameRepository' => 'App\\Repository\\GameRepository',
            'productImageRepository' => 'App\\Repository\\ProductImageRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
