<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_66ORwCMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.66ORwCM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailVerifier' => ['privates', 'App\\Security\\EmailVerifier', 'getEmailVerifierService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'emailVerifier' => 'App\\Security\\EmailVerifier',
            'translator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.66ORwCM'])) {
            return $container->privates['.service_locator.66ORwCM'];
        }

        return $container->privates['.service_locator.66ORwCM'] = $instance;
    }
}
