<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0UnU_TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0UnU._T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gamePopularityService' => ['privates', 'App\\Service\\Catalog\\GamePopularityService', 'getGamePopularityServiceService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'imageUploader' => ['privates', 'App\\Service\\Media\\ImageUploader', 'getImageUploaderService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'entityManager' => '?',
            'gamePopularityService' => 'App\\Service\\Catalog\\GamePopularityService',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'imageUploader' => 'App\\Service\\Media\\ImageUploader',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.0UnU._T'])) {
            return $container->privates['.service_locator.0UnU._T'];
        }

        return $container->privates['.service_locator.0UnU._T'] = $instance;
    }
}
