<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQsrZI3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wQsrZI3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQsrZI3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
