<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yg7fP14Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yg7fP14' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yg7fP14'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedPostAssembler' => ['privates', 'App\\Service\\Post\\FeedPostAssembler', 'getFeedPostAssemblerService', true],
        ], [
            'feedPostAssembler' => 'App\\Service\\Post\\FeedPostAssembler',
        ]);
    }
}
