<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E5txY7aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5txY7a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameFavoriteRepository' => ['privates', 'App\\Repository\\GameFavoriteRepository', 'getGameFavoriteRepositoryService', true],
            'gamePopularityService' => ['privates', 'App\\Service\\Catalog\\GamePopularityService', 'getGamePopularityServiceService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gameFavoriteRepository' => 'App\\Repository\\GameFavoriteRepository',
            'gamePopularityService' => 'App\\Service\\Catalog\\GamePopularityService',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
        ]);

        if (isset($container->privates['.service_locator.e5txY7a'])) {
            return $container->privates['.service_locator.e5txY7a'];
        }

        return $container->privates['.service_locator.e5txY7a'] = $instance;
    }
}
