<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BMHRIMlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bMHRIMl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartManager' => ['privates', 'App\\Service\\Shop\\CartManager', 'getCartManagerService', true],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'productImageRepository' => ['privates', 'App\\Repository\\ProductImageRepository', 'getProductImageRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
        ], [
            'cartManager' => 'App\\Service\\Shop\\CartManager',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'productImageRepository' => 'App\\Repository\\ProductImageRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);

        if (isset($container->privates['.service_locator.bMHRIMl'])) {
            return $container->privates['.service_locator.bMHRIMl'];
        }

        return $container->privates['.service_locator.bMHRIMl'] = $instance;
    }
}
