<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BmsnBUpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bmsnBUp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bmsnBUp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameAiAssistant' => ['privates', 'App\\Service\\Ai\\Game\\GameAiAssistant', 'getGameAiAssistantService', true],
        ], [
            'gameAiAssistant' => 'App\\Service\\Ai\\Game\\GameAiAssistant',
        ]);
    }
}
