<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameAiAssistantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\Game\GameAiAssistant' shared autowired service.
     *
     * @return \App\Service\Ai\Game\GameAiAssistant
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'GameAiAssistant.php';

        return $container->privates['App\\Service\\Ai\\Game\\GameAiAssistant'] = new \App\Service\Ai\Game\GameAiAssistant(($container->privates['App\\Service\\Ai\\Game\\GameAiRemoteClient'] ?? $container->load('getGameAiRemoteClientService')));
    }
}
