<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModerationFeedbackFormatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\Moderation\ModerationFeedbackFormatter' shared autowired service.
     *
     * @return \App\Service\Ai\Moderation\ModerationFeedbackFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'Moderation'.\DIRECTORY_SEPARATOR.'ModerationFeedbackFormatter.php';

        return $container->privates['App\\Service\\Ai\\Moderation\\ModerationFeedbackFormatter'] = new \App\Service\Ai\Moderation\ModerationFeedbackFormatter();
    }
}
