<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenStreetMapGeocoderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Geo\OpenStreetMapGeocoder' shared autowired service.
     *
     * @return \App\Service\Geo\OpenStreetMapGeocoder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Geo'.\DIRECTORY_SEPARATOR.'OpenStreetMapGeocoder.php';

        return $container->privates['App\\Service\\Geo\\OpenStreetMapGeocoder'] = new \App\Service\Geo\OpenStreetMapGeocoder(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
