<?php

namespace ContainerLHHxtYe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentAiAssistantServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\TournamentAiAssistantService' shared autowired service.
     *
     * @return \App\Service\Ai\TournamentAiAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'TournamentAiAssistantService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'OllamaClientService.php';

        return $container->privates['App\\Service\\Ai\\TournamentAiAssistantService'] = new \App\Service\Ai\TournamentAiAssistantService(new \App\Service\Ai\OllamaClientService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))));
    }
}
