<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZOGJZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G_zOGJZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'postImageRepository' => ['privates', 'App\\Repository\\PostImageRepository', 'getPostImageRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'reportRepository' => ['privates', 'App\\Repository\\ReportRepository', 'getReportRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
            'postImageRepository' => 'App\\Repository\\PostImageRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
            'reportRepository' => 'App\\Repository\\ReportRepository',
        ]);

        if (isset($container->privates['.service_locator.G_zOGJZ'])) {
            return $container->privates['.service_locator.G_zOGJZ'];
        }

        return $container->privates['.service_locator.G_zOGJZ'] = $instance;
    }
}
