<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EgWU2jZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.egWU2jZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
        ], [
            'entityManager' => '?',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);

        if (isset($container->privates['.service_locator.egWU2jZ'])) {
            return $container->privates['.service_locator.egWU2jZ'];
        }

        return $container->privates['.service_locator.egWU2jZ'] = $instance;
    }
}
