<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZZHeyMUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZZHeyMU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZZHeyMU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'totpService' => ['privates', 'App\\Service\\Security\\TwoFactorTotpService', 'getTwoFactorTotpServiceService', true],
        ], [
            'totpService' => 'App\\Service\\Security\\TwoFactorTotpService',
        ]);
    }
}
