<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Shop\CartManager' shared autowired service.
     *
     * @return \App\Service\Shop\CartManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Shop'.\DIRECTORY_SEPARATOR.'CartManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Shop\\CartManager'])) {
            return $container->privates['App\\Service\\Shop\\CartManager'];
        }

        $instance = new \App\Service\Shop\CartManager($a, ($container->privates['App\\Repository\\CartRepository'] ?? $container->load('getCartRepositoryService')), ($container->privates['App\\Repository\\CartItemRepository'] ?? $container->load('getCartItemRepositoryService')));

        if (isset($container->privates['App\\Service\\Shop\\CartManager'])) {
            return $container->privates['App\\Service\\Shop\\CartManager'];
        }

        return $container->privates['App\\Service\\Shop\\CartManager'] = $instance;
    }
}
