<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Media\ImageUploader' shared autowired service.
     *
     * @return \App\Service\Media\ImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Media'.\DIRECTORY_SEPARATOR.'ImageUploader.php';

        return $container->privates['App\\Service\\Media\\ImageUploader'] = new \App\Service\Media\ImageUploader(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
