<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchTeamRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\MatchTeamRepository' shared autowired service.
     *
     * @return \App\Repository\MatchTeamRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MatchTeamRepository.php';

        return $container->privates['App\\Repository\\MatchTeamRepository'] = new \App\Repository\MatchTeamRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
