<?php

namespace ContainerEYtxzh3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfImageResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Admin\PdfImageResolver' shared autowired service.
     *
     * @return \App\Service\Admin\PdfImageResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'PdfImageResolver.php';

        return $container->privates['App\\Service\\Admin\\PdfImageResolver'] = new \App\Service\Admin\PdfImageResolver(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
