<?php

namespace ContainerWhqUMMu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NbPo0DTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nbPo0DT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nbPo0DT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organizerAiAssistantService' => ['privates', 'App\\Service\\Organizer\\OrganizerAiAssistantService', 'getOrganizerAiAssistantServiceService', true],
            'tournamentRequestRepository' => ['privates', 'App\\Repository\\TournamentRequestRepository', 'getTournamentRequestRepositoryService', true],
        ], [
            'organizerAiAssistantService' => 'App\\Service\\Organizer\\OrganizerAiAssistantService',
            'tournamentRequestRepository' => 'App\\Repository\\TournamentRequestRepository',
        ]);
    }
}
