<?php

namespace ContainerWhqUMMu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H1Kpoe4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H1Kpoe4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'kernel' => ['services', 'kernel', 'getKernelService', false],
            'organizerAiAssistantService' => ['privates', 'App\\Service\\Organizer\\OrganizerAiAssistantService', 'getOrganizerAiAssistantServiceService', true],
        ], [
            'entityManager' => '?',
            'httpClient' => '?',
            'kernel' => '?',
            'organizerAiAssistantService' => 'App\\Service\\Organizer\\OrganizerAiAssistantService',
        ]);

        if (isset($container->privates['.service_locator.H1Kpoe4'])) {
            return $container->privates['.service_locator.H1Kpoe4'];
        }

        return $container->privates['.service_locator.H1Kpoe4'] = $instance;
    }
}
