<?php

namespace ContainerQ2hWdkp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\CartItemType' => ['privates', 'App\\Form\\CartItemType', 'getCartItemTypeService', true],
            'App\\Form\\CartType' => ['privates', 'App\\Form\\CartType', 'getCartTypeService', true],
            'App\\Form\\CategoryType' => ['privates', 'App\\Form\\CategoryType', 'getCategoryTypeService', true],
            'App\\Form\\CommentType' => ['privates', 'App\\Form\\CommentType', 'getCommentTypeService', true],
            'App\\Form\\FriendRequestType' => ['privates', 'App\\Form\\FriendRequestType', 'getFriendRequestTypeService', true],
            'App\\Form\\FriendshipType' => ['privates', 'App\\Form\\FriendshipType', 'getFriendshipTypeService', true],
            'App\\Form\\GameType' => ['privates', 'App\\Form\\GameType', 'getGameTypeService', true],
            'App\\Form\\ImageType' => ['privates', 'App\\Form\\ImageType', 'getImageTypeService', true],
            'App\\Form\\MatchTeamType' => ['privates', 'App\\Form\\MatchTeamType', 'getMatchTeamTypeService', true],
            'App\\Form\\MessageType' => ['privates', 'App\\Form\\MessageType', 'getMessageTypeService', true],
            'App\\Form\\NotificationType' => ['privates', 'App\\Form\\NotificationType', 'getNotificationTypeService', true],
            'App\\Form\\OrderType' => ['privates', 'App\\Form\\OrderType', 'getOrderTypeService', true],
            'App\\Form\\PostImageType' => ['privates', 'App\\Form\\PostImageType', 'getPostImageTypeService', true],
            'App\\Form\\PostLikeType' => ['privates', 'App\\Form\\PostLikeType', 'getPostLikeTypeService', true],
            'App\\Form\\PostType' => ['privates', 'App\\Form\\PostType', 'getPostTypeService', true],
            'App\\Form\\ProductImageType' => ['privates', 'App\\Form\\ProductImageType', 'getProductImageTypeService', true],
            'App\\Form\\ProductType' => ['privates', 'App\\Form\\ProductType', 'getProductTypeService', true],
            'App\\Form\\ReportType' => ['privates', 'App\\Form\\ReportType', 'getReportTypeService', true],
            'App\\Form\\TeamInviteType' => ['privates', 'App\\Form\\TeamInviteType', 'getTeamInviteTypeService', true],
            'App\\Form\\TeamJoinRequestType' => ['privates', 'App\\Form\\TeamJoinRequestType', 'getTeamJoinRequestTypeService', true],
            'App\\Form\\TeamMemberType' => ['privates', 'App\\Form\\TeamMemberType', 'getTeamMemberTypeService', true],
            'App\\Form\\TeamType' => ['privates', 'App\\Form\\TeamType', 'getTeamTypeService', true],
            'App\\Form\\TournamentMatchType' => ['privates', 'App\\Form\\TournamentMatchType', 'getTournamentMatchTypeService', true],
            'App\\Form\\TournamentRequestType' => ['privates', 'App\\Form\\TournamentRequestType', 'getTournamentRequestTypeService', true],
            'App\\Form\\TournamentTeamType' => ['privates', 'App\\Form\\TournamentTeamType', 'getTournamentTeamTypeService', true],
            'App\\Form\\TournamentType' => ['privates', 'App\\Form\\TournamentType', 'getTournamentTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\CartItemType' => '?',
            'App\\Form\\CartType' => '?',
            'App\\Form\\CategoryType' => '?',
            'App\\Form\\CommentType' => '?',
            'App\\Form\\FriendRequestType' => '?',
            'App\\Form\\FriendshipType' => '?',
            'App\\Form\\GameType' => '?',
            'App\\Form\\ImageType' => '?',
            'App\\Form\\MatchTeamType' => '?',
            'App\\Form\\MessageType' => '?',
            'App\\Form\\NotificationType' => '?',
            'App\\Form\\OrderType' => '?',
            'App\\Form\\PostImageType' => '?',
            'App\\Form\\PostLikeType' => '?',
            'App\\Form\\PostType' => '?',
            'App\\Form\\ProductImageType' => '?',
            'App\\Form\\ProductType' => '?',
            'App\\Form\\ReportType' => '?',
            'App\\Form\\TeamInviteType' => '?',
            'App\\Form\\TeamJoinRequestType' => '?',
            'App\\Form\\TeamMemberType' => '?',
            'App\\Form\\TeamType' => '?',
            'App\\Form\\TournamentMatchType' => '?',
            'App\\Form\\TournamentRequestType' => '?',
            'App\\Form\\TournamentTeamType' => '?',
            'App\\Form\\TournamentType' => '?',
            'App\\Form\\UserType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
            yield 6 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 7), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? self::getDataCollector_FormService($container))));
    }
}
