<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LT6w1eiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lT6w1ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'googleRecaptchaVerifier' => ['privates', 'App\\Service\\Security\\GoogleRecaptchaVerifier', 'getGoogleRecaptchaVerifierService', true],
            'imageUploader' => ['privates', 'App\\Service\\Media\\ImageUploader', 'getImageUploaderService', true],
            'openStreetMapGeocoder' => ['privates', 'App\\Service\\Location\\OpenStreetMapGeocoder', 'getOpenStreetMapGeocoderService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
        ], [
            'entityManager' => '?',
            'googleRecaptchaVerifier' => 'App\\Service\\Security\\GoogleRecaptchaVerifier',
            'imageUploader' => 'App\\Service\\Media\\ImageUploader',
            'openStreetMapGeocoder' => 'App\\Service\\Location\\OpenStreetMapGeocoder',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);

        if (isset($container->privates['.service_locator.lT6w1ei'])) {
            return $container->privates['.service_locator.lT6w1ei'];
        }

        return $container->privates['.service_locator.lT6w1ei'] = $instance;
    }
}
