<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHUir6oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CHUir6o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CHUir6o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'geocoder' => ['privates', 'App\\Service\\Location\\OpenStreetMapGeocoder', 'getOpenStreetMapGeocoderService', true],
        ], [
            'geocoder' => 'App\\Service\\Location\\OpenStreetMapGeocoder',
        ]);
    }
}
