<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JRdLCKsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jRdLCKs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'googleRecaptchaVerifier' => ['privates', 'App\\Service\\Security\\GoogleRecaptchaVerifier', 'getGoogleRecaptchaVerifierService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'realtimeNotifier' => ['privates', 'App\\Service\\Realtime\\RealtimeNotifier', 'getRealtimeNotifierService', true],
            'teamChatModerationService' => ['privates', 'App\\Service\\Ai\\TeamChatModerationService', 'getTeamChatModerationServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'googleRecaptchaVerifier' => 'App\\Service\\Security\\GoogleRecaptchaVerifier',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'realtimeNotifier' => 'App\\Service\\Realtime\\RealtimeNotifier',
            'teamChatModerationService' => 'App\\Service\\Ai\\TeamChatModerationService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.jRdLCKs'])) {
            return $container->privates['.service_locator.jRdLCKs'];
        }

        return $container->privates['.service_locator.jRdLCKs'] = $instance;
    }
}
