<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HNlp7dQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HNlp7dQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartManager' => ['privates', 'App\\Service\\Shop\\CartManager', 'getCartManagerService', true],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'cartManager' => 'App\\Service\\Shop\\CartManager',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'entityManager' => '?',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);

        if (isset($container->privates['.service_locator.HNlp7dQ'])) {
            return $container->privates['.service_locator.HNlp7dQ'];
        }

        return $container->privates['.service_locator.HNlp7dQ'] = $instance;
    }
}
