<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PP_FdsXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pP.FdsX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailVerifier' => ['privates', 'App\\Security\\EmailVerifier', 'getEmailVerifierService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'emailVerifier' => 'App\\Security\\EmailVerifier',
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]);

        if (isset($container->privates['.service_locator.pP.FdsX'])) {
            return $container->privates['.service_locator.pP.FdsX'];
        }

        return $container->privates['.service_locator.pP.FdsX'] = $instance;
    }
}
