<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Templating_FilterRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'liip_imagine.templating.filter_runtime' shared service.
     *
     * @return \Liip\ImagineBundle\Templating\LazyFilterRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'liip'.\DIRECTORY_SEPARATOR.'imagine-bundle'.\DIRECTORY_SEPARATOR.'Templating'.\DIRECTORY_SEPARATOR.'LazyFilterRuntime.php';

        $a = ($container->services['liip_imagine.cache.manager'] ?? $container->load('getLiipImagine_Cache_ManagerService'));

        if (isset($container->privates['liip_imagine.templating.filter_runtime'])) {
            return $container->privates['liip_imagine.templating.filter_runtime'];
        }

        $instance = new \Liip\ImagineBundle\Templating\LazyFilterRuntime($a, NULL, NULL);

        if (isset($container->privates['liip_imagine.templating.filter_runtime'])) {
            return $container->privates['liip_imagine.templating.filter_runtime'];
        }

        return $container->privates['liip_imagine.templating.filter_runtime'] = $instance;
    }
}
