<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Cache_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'liip_imagine.cache.manager' shared service.
     *
     * @return \Liip\ImagineBundle\Imagine\Cache\CacheManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'liip'.\DIRECTORY_SEPARATOR.'imagine-bundle'.\DIRECTORY_SEPARATOR.'Imagine'.\DIRECTORY_SEPARATOR.'Cache'.\DIRECTORY_SEPARATOR.'CacheManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'liip'.\DIRECTORY_SEPARATOR.'imagine-bundle'.\DIRECTORY_SEPARATOR.'Imagine'.\DIRECTORY_SEPARATOR.'Cache'.\DIRECTORY_SEPARATOR.'SignerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'liip'.\DIRECTORY_SEPARATOR.'imagine-bundle'.\DIRECTORY_SEPARATOR.'Imagine'.\DIRECTORY_SEPARATOR.'Cache'.\DIRECTORY_SEPARATOR.'Signer.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['liip_imagine.cache.manager'])) {
            return $container->services['liip_imagine.cache.manager'];
        }

        $instance = new \Liip\ImagineBundle\Imagine\Cache\CacheManager(($container->privates['liip_imagine.filter.configuration'] ?? $container->load('getLiipImagine_Filter_ConfigurationService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['liip_imagine.cache.signer'] ??= new \Liip\ImagineBundle\Imagine\Cache\Signer($container->getEnv('APP_SECRET'))), $a, 'default', false);

        if (isset($container->services['liip_imagine.cache.manager'])) {
            return $container->services['liip_imagine.cache.manager'];
        }

        $container->services['liip_imagine.cache.manager'] = $instance;

        $instance->addResolver('default', ($container->services['liip_imagine.cache.resolver.default'] ?? $container->load('getLiipImagine_Cache_Resolver_DefaultService')));
        $instance->addResolver('no_cache', ($container->services['liip_imagine.cache.resolver.no_cache_web_path'] ?? $container->load('getLiipImagine_Cache_Resolver_NoCacheWebPathService')));

        return $instance;
    }
}
