<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\NotificationRepository' shared autowired service.
     *
     * @return \App\Repository\NotificationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'NotificationRepository.php';

        return $container->privates['App\\Repository\\NotificationRepository'] = new \App\Repository\NotificationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
