<?php

namespace ContainerCx40ayj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamChatModerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\TeamChatModerationService' shared autowired service.
     *
     * @return \App\Service\Ai\TeamChatModerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'TeamChatModerationService.php';

        return $container->privates['App\\Service\\Ai\\TeamChatModerationService'] = new \App\Service\Ai\TeamChatModerationService(($container->privates['App\\Service\\Ai\\MessageModerationService'] ?? $container->load('getMessageModerationServiceService')));
    }
}
