<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1OhavPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1OhavP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
        ], [
            'entityManager' => '?',
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
        ]);

        if (isset($container->privates['.service_locator.k1OhavP'])) {
            return $container->privates['.service_locator.k1OhavP'];
        }

        return $container->privates['.service_locator.k1OhavP'] = $instance;
    }
}
