<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MK5Ai4SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MK5Ai4S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reportRepository' => ['privates', 'App\\Repository\\ReportRepository', 'getReportRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reportRepository' => 'App\\Repository\\ReportRepository',
        ]);

        if (isset($container->privates['.service_locator.MK5Ai4S'])) {
            return $container->privates['.service_locator.MK5Ai4S'];
        }

        return $container->privates['.service_locator.MK5Ai4S'] = $instance;
    }
}
