<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDivisionByZeroAnalyzerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Integrity\DivisionByZeroAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Integrity\DivisionByZeroAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Integrity'.\DIRECTORY_SEPARATOR.'DivisionByZeroAnalyzer.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Integrity\\DivisionByZeroAnalyzer'] = new \AhmedBhs\DoctrineDoctor\Analyzer\Integrity\DivisionByZeroAnalyzer(($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')));
    }
}
