<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineCacheAnalyzerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Configuration\DoctrineCacheAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\DoctrineCacheAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'DoctrineCacheAnalyzer.php';

        $a = ($container->privates['doctrine_doctor.entity_manager_with_filtered_metadata'] ?? $container->load('getDoctrineDoctor_EntityManagerWithFilteredMetadataService'));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\DoctrineCacheAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\DoctrineCacheAnalyzer'];
        }

        $instance = new \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\DoctrineCacheAnalyzer($a, ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), 'dev', \dirname(__DIR__, 4));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\DoctrineCacheAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\DoctrineCacheAnalyzer'];
        }

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\DoctrineCacheAnalyzer'] = $instance;
    }
}
