<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAllAnalyzerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Performance\FindAllAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Performance\FindAllAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Performance'.\DIRECTORY_SEPARATOR.'FindAllAnalyzer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'IssueFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'IssueFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'SqlStructureExtractor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'CachedSqlStructureExtractor.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Performance\\FindAllAnalyzer'] = new \AhmedBhs\DoctrineDoctor\Analyzer\Performance\FindAllAnalyzer(($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\IssueFactoryInterface'] ??= new \AhmedBhs\DoctrineDoctor\Factory\IssueFactory()), ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), 99, ($container->privates['doctrine_doctor.null_logger'] ??= new \Psr\Log\NullLogger()), ($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Parser\\SqlStructureExtractor'] ??= new \AhmedBhs\DoctrineDoctor\Analyzer\Parser\CachedSqlStructureExtractor()));
    }
}
