<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatformAnalysisStrategyFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'PlatformAnalysisStrategyFactory.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'] = new \AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), ($container->privates['AhmedBhs\\DoctrineDoctor\\Utils\\DatabasePlatformDetector'] ?? $container->load('getDatabasePlatformDetectorService')));
    }
}
