<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStrictModeAnalyzerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Configuration\StrictModeAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\StrictModeAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'StrictModeAnalyzer.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\StrictModeAnalyzer'] = new \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\StrictModeAnalyzer(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), ($container->privates['AhmedBhs\\DoctrineDoctor\\Utils\\DatabasePlatformDetector'] ?? $container->load('getDatabasePlatformDetectorService')), ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'] ?? $container->load('getPlatformAnalysisStrategyFactoryService')), ($container->privates['doctrine_doctor.null_logger'] ??= new \Psr\Log\NullLogger()));
    }
}
