<?php

namespace ContainerBhUs8Oe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedDemoDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SeedDemoDataCommand' shared autowired service.
     *
     * @return \App\Command\SeedDemoDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SeedDemoDataCommand.php';

        $container->privates['App\\Command\\SeedDemoDataCommand'] = $instance = new \App\Command\SeedDemoDataCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:seed-demo-data');
        $instance->setDescription('Seed demo data (20+ rows per business table).');

        return $instance;
    }
}
