<?php

namespace ContainerGxbboC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__ZtNZF7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ztNZF7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
        ], [
            'entityManager' => '?',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
        ]);

        if (isset($container->privates['.service_locator..ztNZF7'])) {
            return $container->privates['.service_locator..ztNZF7'];
        }

        return $container->privates['.service_locator..ztNZF7'] = $instance;
    }
}
