<?php

namespace ContainerGxbboC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZ2gLXwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yZ2gLXw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartItemRepository' => ['privates', 'App\\Repository\\CartItemRepository', 'getCartItemRepositoryService', true],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cartItemRepository' => 'App\\Repository\\CartItemRepository',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.yZ2gLXw'])) {
            return $container->privates['.service_locator.yZ2gLXw'];
        }

        return $container->privates['.service_locator.yZ2gLXw'] = $instance;
    }
}
