<?php

namespace ContainerGxbboC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JdHICCRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jdHICCR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'totpService' => ['privates', 'App\\Service\\Security\\TwoFactorTotpService', 'getTwoFactorTotpServiceService', true],
        ], [
            'entityManager' => '?',
            'totpService' => 'App\\Service\\Security\\TwoFactorTotpService',
        ]);

        if (isset($container->privates['.service_locator.jdHICCR'])) {
            return $container->privates['.service_locator.jdHICCR'];
        }

        return $container->privates['.service_locator.jdHICCR'] = $instance;
    }
}
