<?php

namespace ContainerGxbboC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CZM68KFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cZM68KF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'matchTeamRepository' => ['privates', 'App\\Repository\\MatchTeamRepository', 'getMatchTeamRepositoryService', true],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'matchTeamRepository' => 'App\\Repository\\MatchTeamRepository',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
        ]);

        if (isset($container->privates['.service_locator.cZM68KF'])) {
            return $container->privates['.service_locator.cZM68KF'];
        }

        return $container->privates['.service_locator.cZM68KF'] = $instance;
    }
}
