<?php

namespace ContainerGxbboC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FriendshipRepository' shared autowired service.
     *
     * @return \App\Repository\FriendshipRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'FriendshipRepository.php';

        return $container->privates['App\\Repository\\FriendshipRepository'] = new \App\Repository\FriendshipRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
