<?php

namespace Container7FoVWZ5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizerAiAssistantServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Organizer\OrganizerAiAssistantService' shared autowired service.
     *
     * @return \App\Service\Organizer\OrganizerAiAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Organizer'.\DIRECTORY_SEPARATOR.'OrganizerAiAssistantService.php';

        return $container->privates['App\\Service\\Organizer\\OrganizerAiAssistantService'] = new \App\Service\Organizer\OrganizerAiAssistantService(($container->privates['App\\Repository\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')));
    }
}
