<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B7EK_OService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.b7EK_.O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'teamRepository' => 'App\\Repository\\TeamRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
        ]);

        if (isset($container->privates['.service_locator.b7EK_.O'])) {
            return $container->privates['.service_locator.b7EK_.O'];
        }

        return $container->privates['.service_locator.b7EK_.O'] = $instance;
    }
}
