<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\Page\\TournamentFormController::index' => ['privates', '.service_locator.noj6eVD', 'get_ServiceLocator_Noj6eVDService', true],
            'App\\Controller\\Front\\Page\\ForgotPasswordController::index' => ['privates', '.service_locator.ikxjD2E', 'get_ServiceLocator_IkxjD2EService', true],
            'App\\Controller\\Front\\Page\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchCreateController::index' => ['privates', '.service_locator.2XgIC_Y', 'get_ServiceLocator_2XgICYService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchEditController::index' => ['privates', '.service_locator.uQreGtu', 'get_ServiceLocator_UQreGtuService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchesController::index' => ['privates', '.service_locator.1zkV4xr', 'get_ServiceLocator_1zkV4xrService', true],
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController::index' => ['privates', '.service_locator..1e.4DY', 'get_ServiceLocator__1e_4DYService', true],
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController::updateStatus' => ['privates', '.service_locator.b7EK_.O', 'get_ServiceLocator_B7EK_OService', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestCreateController::index' => ['privates', '.service_locator.noj6eVD', 'get_ServiceLocator_Noj6eVDService', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestDetailController::index' => ['privates', '.service_locator.lWtJrP.', 'get_ServiceLocator_LWtJrP_Service', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestsController::index' => ['privates', '.service_locator.lWtJrP.', 'get_ServiceLocator_LWtJrP_Service', true],
            'App\\Controller\\Front\\Page\\OrganizerTournamentDetailController::index' => ['privates', '.service_locator.gjvUWEB', 'get_ServiceLocator_GjvUWEBService', true],
            'App\\Controller\\Front\\Page\\OrganizerTournamentsController::index' => ['privates', '.service_locator..1e.4DY', 'get_ServiceLocator__1e_4DYService', true],
            'App\\Controller\\Front\\Page\\RegisterController::index' => ['privates', '.service_locator.pP.FdsX', 'get_ServiceLocator_PP_FdsXService', true],
            'App\\Controller\\Front\\Page\\ResetPasswordController::index' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'App\\Controller\\Security\\VerifyEmailController::verifyUserEmail' => ['privates', '.service_locator.66ORwCM', 'get_ServiceLocator_66ORwCMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\Page\\TournamentFormController:index' => ['privates', '.service_locator.noj6eVD', 'get_ServiceLocator_Noj6eVDService', true],
            'App\\Controller\\Front\\Page\\ForgotPasswordController:index' => ['privates', '.service_locator.ikxjD2E', 'get_ServiceLocator_IkxjD2EService', true],
            'App\\Controller\\Front\\Page\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchCreateController:index' => ['privates', '.service_locator.2XgIC_Y', 'get_ServiceLocator_2XgICYService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchEditController:index' => ['privates', '.service_locator.uQreGtu', 'get_ServiceLocator_UQreGtuService', true],
            'App\\Controller\\Front\\Page\\OrganizerMatchesController:index' => ['privates', '.service_locator.1zkV4xr', 'get_ServiceLocator_1zkV4xrService', true],
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController:index' => ['privates', '.service_locator..1e.4DY', 'get_ServiceLocator__1e_4DYService', true],
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController:updateStatus' => ['privates', '.service_locator.b7EK_.O', 'get_ServiceLocator_B7EK_OService', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestCreateController:index' => ['privates', '.service_locator.noj6eVD', 'get_ServiceLocator_Noj6eVDService', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestDetailController:index' => ['privates', '.service_locator.lWtJrP.', 'get_ServiceLocator_LWtJrP_Service', true],
            'App\\Controller\\Front\\Page\\OrganizerRequestsController:index' => ['privates', '.service_locator.lWtJrP.', 'get_ServiceLocator_LWtJrP_Service', true],
            'App\\Controller\\Front\\Page\\OrganizerTournamentDetailController:index' => ['privates', '.service_locator.gjvUWEB', 'get_ServiceLocator_GjvUWEBService', true],
            'App\\Controller\\Front\\Page\\OrganizerTournamentsController:index' => ['privates', '.service_locator..1e.4DY', 'get_ServiceLocator__1e_4DYService', true],
            'App\\Controller\\Front\\Page\\RegisterController:index' => ['privates', '.service_locator.pP.FdsX', 'get_ServiceLocator_PP_FdsXService', true],
            'App\\Controller\\Front\\Page\\ResetPasswordController:index' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'App\\Controller\\Security\\VerifyEmailController:verifyUserEmail' => ['privates', '.service_locator.66ORwCM', 'get_ServiceLocator_66ORwCMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\Page\\TournamentFormController::index' => '?',
            'App\\Controller\\Front\\Page\\ForgotPasswordController::index' => '?',
            'App\\Controller\\Front\\Page\\LoginController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchCreateController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchEditController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchesController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController::updateStatus' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestCreateController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestDetailController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestsController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerTournamentDetailController::index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerTournamentsController::index' => '?',
            'App\\Controller\\Front\\Page\\RegisterController::index' => '?',
            'App\\Controller\\Front\\Page\\ResetPasswordController::index' => '?',
            'App\\Controller\\Security\\VerifyEmailController::verifyUserEmail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\Page\\TournamentFormController:index' => '?',
            'App\\Controller\\Front\\Page\\ForgotPasswordController:index' => '?',
            'App\\Controller\\Front\\Page\\LoginController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchCreateController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchEditController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerMatchesController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRegistrationsController:updateStatus' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestCreateController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestDetailController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerRequestsController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerTournamentDetailController:index' => '?',
            'App\\Controller\\Front\\Page\\OrganizerTournamentsController:index' => '?',
            'App\\Controller\\Front\\Page\\RegisterController:index' => '?',
            'App\\Controller\\Front\\Page\\ResetPasswordController:index' => '?',
            'App\\Controller\\Security\\VerifyEmailController:verifyUserEmail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
