<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Page\CartsController' shared autowired service.
     *
     * @return \App\Controller\Admin\Page\CartsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Page\\CartsController'] = $instance = new \App\Controller\Admin\Page\CartsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\Page\\CartsController', $container));

        return $instance;
    }
}
