<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Front\Page\FeedController' shared autowired service.
     *
     * @return \App\Controller\Front\Page\FeedController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Front\\Page\\FeedController'] = $instance = new \App\Controller\Front\Page\FeedController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Front\\Page\\FeedController', $container));

        return $instance;
    }
}
