<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileEditControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Front\Page\ProfileEditController' shared autowired service.
     *
     * @return \App\Controller\Front\Page\ProfileEditController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Front\\Page\\ProfileEditController'] = $instance = new \App\Controller\Front\Page\ProfileEditController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Front\\Page\\ProfileEditController', $container));

        return $instance;
    }
}
