<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamJoinRequestRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TeamJoinRequestRepository' shared autowired service.
     *
     * @return \App\Repository\TeamJoinRequestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TeamJoinRequestRepository'] = new \App\Repository\TeamJoinRequestRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
