<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamMemberRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TeamMemberRepository' shared autowired service.
     *
     * @return \App\Repository\TeamMemberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TeamMemberRepository'] = new \App\Repository\TeamMemberRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
