<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRequestsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Page\TournamentRequestsController' shared autowired service.
     *
     * @return \App\Controller\Admin\Page\TournamentRequestsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Page\\TournamentRequestsController'] = $instance = new \App\Controller\Admin\Page\TournamentRequestsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\Page\\TournamentRequestsController', $container));

        return $instance;
    }
}
