<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Page\UsersController' shared autowired service.
     *
     * @return \App\Controller\Admin\Page\UsersController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Page\\UsersController'] = $instance = new \App\Controller\Admin\Page\UsersController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\Page\\UsersController', $container));

        return $instance;
    }
}
