<?php

namespace ContainerCOvGFMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyEmailControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Security\VerifyEmailController' shared autowired service.
     *
     * @return \App\Controller\Security\VerifyEmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Security\\VerifyEmailController'] = $instance = new \App\Controller\Security\VerifyEmailController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Security\\VerifyEmailController', $container));

        return $instance;
    }
}
