<?php

namespace ContainerQlhkx2N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F_KJrjRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f.kJrjR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f.kJrjR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'teamJoinRequestRepository' => ['privates', 'App\\Repository\\TeamJoinRequestRepository', 'getTeamJoinRequestRepositoryService', true],
        ], [
            'teamJoinRequestRepository' => 'App\\Repository\\TeamJoinRequestRepository',
        ]);
    }
}
