<?php

namespace ContainerQlhkx2N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Admin\TableExportService' shared autowired service.
     *
     * @return \App\Service\Admin\TableExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'TableExportService.php';

        return $container->privates['App\\Service\\Admin\\TableExportService'] = new \App\Service\Admin\TableExportService();
    }
}
