<?php

namespace ContainerXxrMA9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KaSLNmJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KaSLNmJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KaSLNmJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchAiAssistantService' => ['privates', 'App\\Service\\Ai\\MatchAiAssistantService', 'getMatchAiAssistantServiceService', true],
            'matchTeamRepository' => ['privates', 'App\\Repository\\MatchTeamRepository', 'getMatchTeamRepositoryService', true],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
        ], [
            'matchAiAssistantService' => 'App\\Service\\Ai\\MatchAiAssistantService',
            'matchTeamRepository' => 'App\\Repository\\MatchTeamRepository',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
        ]);
    }
}
