<?php

namespace ContainerXxrMA9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9h7qmdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A9h7qmd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'matchAiAssistantService' => ['privates', 'App\\Service\\Ai\\MatchAiAssistantService', 'getMatchAiAssistantServiceService', true],
            'matchTeamRepository' => ['privates', 'App\\Repository\\MatchTeamRepository', 'getMatchTeamRepositoryService', true],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'matchAiAssistantService' => 'App\\Service\\Ai\\MatchAiAssistantService',
            'matchTeamRepository' => 'App\\Repository\\MatchTeamRepository',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
        ]);

        if (isset($container->privates['.service_locator.A9h7qmd'])) {
            return $container->privates['.service_locator.A9h7qmd'];
        }

        return $container->privates['.service_locator.A9h7qmd'] = $instance;
    }
}
