<?php

namespace ContainerXxrMA9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2lGKaAvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2lGKaAv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2lGKaAv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
        ]);
    }
}
