<?php

namespace ContainerX6sNPzk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0yItc9UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0yItc9U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploader' => ['privates', 'App\\Service\\Media\\ImageUploader', 'getImageUploaderService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'imageUploader' => 'App\\Service\\Media\\ImageUploader',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.0yItc9U'])) {
            return $container->privates['.service_locator.0yItc9U'];
        }

        return $container->privates['.service_locator.0yItc9U'] = $instance;
    }
}
