<?php

namespace ContainerX6sNPzk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TdT8Eo7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TdT8Eo7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TdT8Eo7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'reportRepository' => ['privates', 'App\\Repository\\ReportRepository', 'getReportRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
            'reportRepository' => 'App\\Repository\\ReportRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
