<?php

namespace ContainerCvGvgwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TOnKRgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tOn_KRg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captainTeamContextProvider' => ['privates', 'App\\Service\\Captain\\CaptainTeamContextProvider', 'getCaptainTeamContextProviderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'invitationMessageAssistant' => ['privates', 'App\\Service\\Ai\\InvitationMessageAssistant', 'getInvitationMessageAssistantService', true],
            'messageModerationService' => ['privates', 'App\\Service\\Ai\\MessageModerationService', 'getMessageModerationServiceService', true],
            'realtimeNotifier' => ['privates', 'App\\Service\\Realtime\\RealtimeNotifier', 'getRealtimeNotifierService', true],
            'rosterManager' => ['privates', 'App\\Service\\Captain\\RosterManager', 'getRosterManagerService', true],
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'captainTeamContextProvider' => 'App\\Service\\Captain\\CaptainTeamContextProvider',
            'entityManager' => '?',
            'invitationMessageAssistant' => 'App\\Service\\Ai\\InvitationMessageAssistant',
            'messageModerationService' => 'App\\Service\\Ai\\MessageModerationService',
            'realtimeNotifier' => 'App\\Service\\Realtime\\RealtimeNotifier',
            'rosterManager' => 'App\\Service\\Captain\\RosterManager',
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.tOn_KRg'])) {
            return $container->privates['.service_locator.tOn_KRg'];
        }

        return $container->privates['.service_locator.tOn_KRg'] = $instance;
    }
}
