<?php

namespace ContainerCvGvgwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Media\ImageUploader' shared autowired service.
     *
     * @return \App\Service\Media\ImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Media'.\DIRECTORY_SEPARATOR.'ImageUploader.php';

        return $container->privates['App\\Service\\Media\\ImageUploader'] = new \App\Service\Media\ImageUploader(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('string:CLOUDINARY_CLOUD_NAME'), $container->getEnv('string:CLOUDINARY_API_KEY'), $container->getEnv('string:CLOUDINARY_API_SECRET'), $container->getEnv('string:CLOUDINARY_FOLDER'));
    }
}
