<?php

namespace ContainerCvGvgwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationMessageAssistantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\InvitationMessageAssistant' shared autowired service.
     *
     * @return \App\Service\Ai\InvitationMessageAssistant
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'InvitationMessageAssistant.php';

        return $container->privates['App\\Service\\Ai\\InvitationMessageAssistant'] = new \App\Service\Ai\InvitationMessageAssistant(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('string:OPENAI_API_KEY'), $container->getEnv('string:OPENAI_MODEL'), $container->getEnv('bool:PULSE_AI_ENABLE_REMOTE'));
    }
}
