<?php

namespace ContainerCvGvgwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageModerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Ai\MessageModerationService' shared autowired service.
     *
     * @return \App\Service\Ai\MessageModerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ai'.\DIRECTORY_SEPARATOR.'MessageModerationService.php';

        return $container->privates['App\\Service\\Ai\\MessageModerationService'] = new \App\Service\Ai\MessageModerationService($container->parameters['app.message_moderation.spam_terms'], $container->parameters['app.message_moderation.toxic_terms']);
    }
}
