<?php

namespace ContainerCvGvgwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealtimeNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Realtime\RealtimeNotifier' shared autowired service.
     *
     * @return \App\Service\Realtime\RealtimeNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Realtime'.\DIRECTORY_SEPARATOR.'RealtimeNotifier.php';

        return $container->privates['App\\Service\\Realtime\\RealtimeNotifier'] = new \App\Service\Realtime\RealtimeNotifier(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
