<?php

namespace ContainerOZOHdPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGnkaDaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qGnkaDa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teamJoinRequestRepository' => ['privates', 'App\\Repository\\TeamJoinRequestRepository', 'getTeamJoinRequestRepositoryService', true],
        ], [
            'entityManager' => '?',
            'teamJoinRequestRepository' => 'App\\Repository\\TeamJoinRequestRepository',
        ]);

        if (isset($container->privates['.service_locator.qGnkaDa'])) {
            return $container->privates['.service_locator.qGnkaDa'];
        }

        return $container->privates['.service_locator.qGnkaDa'] = $instance;
    }
}
