<?php

namespace ContainerOZOHdPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GjvUWEBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gjvUWEB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'kernel' => ['services', 'kernel', 'getKernelService', false],
            'tournamentMatchRepository' => ['privates', 'App\\Repository\\TournamentMatchRepository', 'getTournamentMatchRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentTeamRepository' => ['privates', 'App\\Repository\\TournamentTeamRepository', 'getTournamentTeamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'kernel' => '?',
            'tournamentMatchRepository' => 'App\\Repository\\TournamentMatchRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentTeamRepository' => 'App\\Repository\\TournamentTeamRepository',
        ]);

        if (isset($container->privates['.service_locator.gjvUWEB'])) {
            return $container->privates['.service_locator.gjvUWEB'];
        }

        return $container->privates['.service_locator.gjvUWEB'] = $instance;
    }
}
