<?php

namespace ContainerOZOHdPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Db6eGdRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.db6eGdR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.db6eGdR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
        ]);
    }
}
