<?php

namespace ContainerOZOHdPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DVAN9daService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DVAN9da' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DVAN9da'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'tableExportService' => ['privates', 'App\\Service\\Admin\\TableExportService', 'getTableExportServiceService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', false],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'tableExportService' => 'App\\Service\\Admin\\TableExportService',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);
    }
}
