<?php

namespace ContainerJ3aUrxQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UR8xdnKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UR8xdnK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UR8xdnK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'friendRequestRepository' => ['privates', 'App\\Repository\\FriendRequestRepository', 'getFriendRequestRepositoryService', true],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
        ], [
            'friendRequestRepository' => 'App\\Repository\\FriendRequestRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
        ]);
    }
}
