<?php

namespace ContainerJ3aUrxQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Abtyb8WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Abtyb8W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Abtyb8W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ollamaClientService' => ['privates', 'App\\Service\\Ai\\OllamaClientService', 'getOllamaClientServiceService', true],
        ], [
            'ollamaClientService' => 'App\\Service\\Ai\\OllamaClientService',
        ]);
    }
}
