<?php

namespace ContainerJ3aUrxQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DTTxNmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d_TTxNm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_TTxNm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'teamInviteRepository' => ['privates', 'App\\Repository\\TeamInviteRepository', 'getTeamInviteRepositoryService', true],
            'teamMemberRepository' => ['privates', 'App\\Repository\\TeamMemberRepository', 'getTeamMemberRepositoryService', true],
        ], [
            'teamInviteRepository' => 'App\\Repository\\TeamInviteRepository',
            'teamMemberRepository' => 'App\\Repository\\TeamMemberRepository',
        ]);
    }
}
