<?php

namespace ContainerJ3aUrxQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostLikeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PostLikeRepository' shared autowired service.
     *
     * @return \App\Repository\PostLikeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PostLikeRepository.php';

        return $container->privates['App\\Repository\\PostLikeRepository'] = new \App\Repository\PostLikeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
