<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8o8357\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8o8357/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH8o8357.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH8o8357\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH8o8357\App_KernelDevDebugContainer([
    'container.build_hash' => 'H8o8357',
    'container.build_id' => 'd4bc2ec0',
    'container.build_time' => 1771718533,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8o8357');
