<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHHxtYe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHHxtYe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHHxtYe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHHxtYe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHHxtYe\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHHxtYe',
    'container.build_id' => '63eb847b',
    'container.build_time' => 1772177295,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHHxtYe');
