<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3aUrxQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3aUrxQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ3aUrxQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ3aUrxQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ3aUrxQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'J3aUrxQ',
    'container.build_id' => '5eabcc05',
    'container.build_time' => 1772125987,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3aUrxQ');
