<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TeamInvite extends \App\Entity\TeamInvite implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'inviteId' => [parent::class, 'inviteId', null, 16],
        "\0".parent::class."\0".'invitedByUserId' => [parent::class, 'invitedByUserId', null, 16],
        "\0".parent::class."\0".'invitedUserId' => [parent::class, 'invitedUserId', null, 16],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null, 16],
        "\0".parent::class."\0".'respondedAt' => [parent::class, 'respondedAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'teamId' => [parent::class, 'teamId', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'inviteId' => [parent::class, 'inviteId', null, 16],
        'invitedByUserId' => [parent::class, 'invitedByUserId', null, 16],
        'invitedUserId' => [parent::class, 'invitedUserId', null, 16],
        'message' => [parent::class, 'message', null, 16],
        'respondedAt' => [parent::class, 'respondedAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'teamId' => [parent::class, 'teamId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
