<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournament extends \App\Entity\Tournament implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null, 16],
        "\0".parent::class."\0".'format' => [parent::class, 'format', null, 16],
        "\0".parent::class."\0".'gameId' => [parent::class, 'gameId', null, 16],
        "\0".parent::class."\0".'maxTeams' => [parent::class, 'maxTeams', null, 16],
        "\0".parent::class."\0".'organizerUserId' => [parent::class, 'organizerUserId', null, 16],
        "\0".parent::class."\0".'photoPath' => [parent::class, 'photoPath', null, 16],
        "\0".parent::class."\0".'prizeDescription' => [parent::class, 'prizeDescription', null, 16],
        "\0".parent::class."\0".'prizePool' => [parent::class, 'prizePool', null, 16],
        "\0".parent::class."\0".'registrationDeadline' => [parent::class, 'registrationDeadline', null, 16],
        "\0".parent::class."\0".'registrationMode' => [parent::class, 'registrationMode', null, 16],
        "\0".parent::class."\0".'rules' => [parent::class, 'rules', null, 16],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'tournamentId' => [parent::class, 'tournamentId', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'endDate' => [parent::class, 'endDate', null, 16],
        'format' => [parent::class, 'format', null, 16],
        'gameId' => [parent::class, 'gameId', null, 16],
        'maxTeams' => [parent::class, 'maxTeams', null, 16],
        'organizerUserId' => [parent::class, 'organizerUserId', null, 16],
        'photoPath' => [parent::class, 'photoPath', null, 16],
        'prizeDescription' => [parent::class, 'prizeDescription', null, 16],
        'prizePool' => [parent::class, 'prizePool', null, 16],
        'registrationDeadline' => [parent::class, 'registrationDeadline', null, 16],
        'registrationMode' => [parent::class, 'registrationMode', null, 16],
        'rules' => [parent::class, 'rules', null, 16],
        'startDate' => [parent::class, 'startDate', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'tournamentId' => [parent::class, 'tournamentId', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
