<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cartId' => [parent::class, 'cartId', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'deliveredAt' => [parent::class, 'deliveredAt', null, 16],
        "\0".parent::class."\0".'orderId' => [parent::class, 'orderId', null, 16],
        "\0".parent::class."\0".'orderNumber' => [parent::class, 'orderNumber', null, 16],
        "\0".parent::class."\0".'paidAt' => [parent::class, 'paidAt', null, 16],
        "\0".parent::class."\0".'paymentMethod' => [parent::class, 'paymentMethod', null, 16],
        "\0".parent::class."\0".'paymentStatus' => [parent::class, 'paymentStatus', null, 16],
        "\0".parent::class."\0".'phoneForDelivery' => [parent::class, 'phoneForDelivery', null, 16],
        "\0".parent::class."\0".'shippedAt' => [parent::class, 'shippedAt', null, 16],
        "\0".parent::class."\0".'shippingAddress' => [parent::class, 'shippingAddress', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'totalAmount' => [parent::class, 'totalAmount', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        'cartId' => [parent::class, 'cartId', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deliveredAt' => [parent::class, 'deliveredAt', null, 16],
        'orderId' => [parent::class, 'orderId', null, 16],
        'orderNumber' => [parent::class, 'orderNumber', null, 16],
        'paidAt' => [parent::class, 'paidAt', null, 16],
        'paymentMethod' => [parent::class, 'paymentMethod', null, 16],
        'paymentStatus' => [parent::class, 'paymentStatus', null, 16],
        'phoneForDelivery' => [parent::class, 'phoneForDelivery', null, 16],
        'shippedAt' => [parent::class, 'shippedAt', null, 16],
        'shippingAddress' => [parent::class, 'shippingAddress', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'totalAmount' => [parent::class, 'totalAmount', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
