<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CartItem extends \App\Entity\CartItem implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addedAt' => [parent::class, 'addedAt', null, 16],
        "\0".parent::class."\0".'cartId' => [parent::class, 'cartId', null, 16],
        "\0".parent::class."\0".'productId' => [parent::class, 'productId', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'unitPriceAtAdd' => [parent::class, 'unitPriceAtAdd', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'addedAt' => [parent::class, 'addedAt', null, 16],
        'cartId' => [parent::class, 'cartId', null, 16],
        'productId' => [parent::class, 'productId', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'unitPriceAtAdd' => [parent::class, 'unitPriceAtAdd', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
