<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TournamentTeam extends \App\Entity\TournamentTeam implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'checkedIn' => [parent::class, 'checkedIn', null, 16],
        "\0".parent::class."\0".'checkinAt' => [parent::class, 'checkinAt', null, 16],
        "\0".parent::class."\0".'decidedAt' => [parent::class, 'decidedAt', null, 16],
        "\0".parent::class."\0".'decidedByUserId' => [parent::class, 'decidedByUserId', null, 16],
        "\0".parent::class."\0".'registeredAt' => [parent::class, 'registeredAt', null, 16],
        "\0".parent::class."\0".'seed' => [parent::class, 'seed', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'teamId' => [parent::class, 'teamId', null, 16],
        "\0".parent::class."\0".'tournamentId' => [parent::class, 'tournamentId', null, 16],
        'checkedIn' => [parent::class, 'checkedIn', null, 16],
        'checkinAt' => [parent::class, 'checkinAt', null, 16],
        'decidedAt' => [parent::class, 'decidedAt', null, 16],
        'decidedByUserId' => [parent::class, 'decidedByUserId', null, 16],
        'registeredAt' => [parent::class, 'registeredAt', null, 16],
        'seed' => [parent::class, 'seed', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'teamId' => [parent::class, 'teamId', null, 16],
        'tournamentId' => [parent::class, 'tournamentId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
