<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'authorUserId' => [parent::class, 'authorUserId', null, 16],
        "\0".parent::class."\0".'contentText' => [parent::class, 'contentText', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null, 16],
        "\0".parent::class."\0".'isDeleted' => [parent::class, 'isDeleted', null, 16],
        "\0".parent::class."\0".'postId' => [parent::class, 'postId', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'visibility' => [parent::class, 'visibility', null, 16],
        'authorUserId' => [parent::class, 'authorUserId', null, 16],
        'contentText' => [parent::class, 'contentText', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 16],
        'isDeleted' => [parent::class, 'isDeleted', null, 16],
        'postId' => [parent::class, 'postId', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'visibility' => [parent::class, 'visibility', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
