<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \App\Entity\Message implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bodyText' => [parent::class, 'bodyText', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'isDeletedByReceiver' => [parent::class, 'isDeletedByReceiver', null, 16],
        "\0".parent::class."\0".'isDeletedBySender' => [parent::class, 'isDeletedBySender', null, 16],
        "\0".parent::class."\0".'isRead' => [parent::class, 'isRead', null, 16],
        "\0".parent::class."\0".'messageId' => [parent::class, 'messageId', null, 16],
        "\0".parent::class."\0".'readAt' => [parent::class, 'readAt', null, 16],
        "\0".parent::class."\0".'receiverUserId' => [parent::class, 'receiverUserId', null, 16],
        "\0".parent::class."\0".'senderUserId' => [parent::class, 'senderUserId', null, 16],
        'bodyText' => [parent::class, 'bodyText', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'isDeletedByReceiver' => [parent::class, 'isDeletedByReceiver', null, 16],
        'isDeletedBySender' => [parent::class, 'isDeletedBySender', null, 16],
        'isRead' => [parent::class, 'isRead', null, 16],
        'messageId' => [parent::class, 'messageId', null, 16],
        'readAt' => [parent::class, 'readAt', null, 16],
        'receiverUserId' => [parent::class, 'receiverUserId', null, 16],
        'senderUserId' => [parent::class, 'senderUserId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
