<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MatchTeam extends \App\Entity\MatchTeam implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'isWinner' => [parent::class, 'isWinner', null, 16],
        "\0".parent::class."\0".'matchId' => [parent::class, 'matchId', null, 16],
        "\0".parent::class."\0".'score' => [parent::class, 'score', null, 16],
        "\0".parent::class."\0".'teamId' => [parent::class, 'teamId', null, 16],
        'isWinner' => [parent::class, 'isWinner', null, 16],
        'matchId' => [parent::class, 'matchId', null, 16],
        'score' => [parent::class, 'score', null, 16],
        'teamId' => [parent::class, 'teamId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
